### ISSUE TITLE
Possible unsolved money bug

### ISSUE THREAD

**Issue by xPix3l** [Zrips/TradeMeAddon#1]
When I use TradeMe to trade and I exchange money with another player, sometimes, the money are not changed, I lose nothing and the other user earns them. So if I exchange 100$ in a normal trade I lose nothing but the other player gets them. I think there is the risk to lose own money without any gain... **Have you already solved?**

**Comment by Rukes** [comment]
I think this has been fixed 😺

**Comment by xPix3l** [comment]
I think it too.
