### ISSUE TITLE
TradeMe can't check for new version

### ISSUE THREAD

**Issue by mrfloris** [Zrips/TradeMeAddon#18]
```
[14:11:58] [Craft Scheduler Thread - 76/INFO]: Failed to check for TradeMe update on spigot web page.
```

Just like CMI, all zrips plugins need an update to support the now deprecated check for new version api from spigot, including trademe.

**Comment by mrfloris** [comment]
Thank you for the new version, it's still having an issue checking versions. The last few releases, the version has been one behind, but it isn't. 

SpigotMC.org gives:

6.0.2.2 | Monday at 4:59 PM | 63 | 0 ratings | Download =>> `TradeMe6.0.2.2.jar`

The plugins/ directory has listed: `TradeMe6.0.2.2.jar`

The server obviously has been /stopped and started.

```
>ver TradeMe
[02:33:58] [Server thread/INFO]: TradeMe version 6.0.2.1
[02:33:58] [Server thread/INFO]: Powerfull trade plugin
[02:33:58] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/trademe.7544/
[02:33:58] [Server thread/INFO]: Author: Zrips
>
```

In-game it says:

<img width="486" alt="Screenshot 2020-02-13 at 02 37 15" src="https://user-images.githubusercontent.com/28841349/74393230-c1b8b000-4e09-11ea-8474-ad5a33ca3e42.png">


The first two updates, I thought I was simply wrong and didn't overwrite or whatever, but specifically tested it and it's a version behind.

**Comment by Zrips** [comment]
Fixed by using CMILib plugin as of 7.x version
