### ISSUE TITLE
Wrong version ID

### ISSUE THREAD

**Issue by eternitymoe** [Zrips/TradeMeAddon#19]
<img width="280" alt="Screenshot 2020-03-01 at 17 04 44" src="https://user-images.githubusercontent.com/44344308/75622758-da351280-5bde-11ea-8da6-3125545082b4.png">
<img width="338" alt="Screenshot 2020-03-01 at 17 04 39" src="https://user-images.githubusercontent.com/44344308/75622761-e15c2080-5bde-11ea-8b21-34b3fd548543.png">
<img width="444" alt="Screenshot 2020-03-01 at 17 05 35" src="https://user-images.githubusercontent.com/44344308/75622763-e3be7a80-5bde-11ea-98a8-b61c8023f08b.png">
I downloaded version 6.0.2.2 form spigotmc, and the version id is 6.0.2.1

**Comment by mrfloris** [comment]
<img width="993" alt="Screenshot 2020-03-02 at 09 27 36" src="https://user-images.githubusercontent.com/28841349/75658216-2710fb80-5c68-11ea-9f94-b92e2b227d7d.png">
<img width="898" alt="Screenshot 2020-03-02 at 09 27 45" src="https://user-images.githubusercontent.com/28841349/75658218-28422880-5c68-11ea-9f6e-962d334cc5e5.png">

confirmed, shows me the old version, downloads as newer version, but it's .. well you get it.

Config.yml, would be nice if we had a toggle there to not check for version on join of oper to chat

**Comment by Zrips** [comment]
Should be resolved
