### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MERRYACS** [Zrips/TradeMeAddon#24]
Spigot 1.12.2
TradeMe Version: 6.0.3.4

Bug:
the BlockedItem function no work(it work in the old version)
the BlockedLore function not work at all
When I test i don't give myself OP, because ik there is a bypass permission.

**Comment by MERRYACS** [comment]
One more bug:
While player trade, if one player opening a chest/gui while other player accepting the trade. it will bug. Other player's trade window still open. but he can't trade. and if he put items in there and then press esc. the items will lost

**Comment by Zrips** [comment]
Should be resolved
