### ISSUE TITLE
Weird bug that breaks the plugin and clears the players inventory 

### ISSUE THREAD

**Issue by ghost** [Zrips/TradeMeAddon#27]
![image](https://user-images.githubusercontent.com/23074182/86017872-29893380-ba57-11ea-8045-8a1d50150a02.png)
Console Log (The only error from TradeMe)
``[Mon, 29. Jun 2020 22:16:45 SGT ERROR] Could not pass event InventoryClickEvent to TradeMe v6.0.4.0``

**Comment by ghost** [comment]
Any news?

**Comment by Zrips** [comment]
Should be resolved
