### ISSUE TITLE
Players cant see when someone sends a trade request. Also plugin is broken.

### ISSUE THREAD

**Issue by Duqino** [Zrips/TradeMeAddon#3]
I already asked the maker of chatcontrole if his plugin can cause this problem. And he said no.

```
20.09 18:16:06 [Server] INFO gijsvdvoet issued server command: /trade time_men
20.09 18:16:06 [Server] INFO Expected whitespace to end one argument, but found trailing data
20.09 18:16:06 [Server] INFO ...},"clickEvent":{"action":"run_command","value":"/trade deny"}}]<--[HERE]
20.09 18:16:07 [Server] INFO Time_Men issued server command: /trade accept

```

Some how the players cant see anything in chat that some one send them a trade request. The /trade accept command does work fine.

No errors.

------------

After updating the server to the latest spigot version the plugin stopped working.

https://pastebin.com/k293im5x

**Comment by Duqino** [comment]
Error in console -> https://pastebin.com/muQ8jgPY

**Comment by Zrips** [comment]
Should be resolved
