### ISSUE TITLE
Version issue on 6.0.4.2

### ISSUE THREAD

**Issue by dragontekgaming** [Zrips/TradeMeAddon#35]
In game version shows 6.0.4.1, and tells me to update on downloaded version TradeMe6.0.4.2.jar
![image](https://user-images.githubusercontent.com/67290518/90966458-d5676200-e48f-11ea-9cda-515d58948939.png)
![image](https://user-images.githubusercontent.com/67290518/90966475-fa5bd500-e48f-11ea-8094-6e670b22d948.png)

Downloaded file from the Spigot page.

**Comment by AcesGamingUK** [comment]
i too have this issue, quite annoying
![image](https://user-images.githubusercontent.com/16180389/92328218-fa92cd80-f056-11ea-9a5e-781e50efe082.png)

**Comment by Zrips** [comment]
Will be fixed with next update
