### ISSUE TITLE
Errors when running /trade {player} 1.13.1

### ISSUE THREAD

**Issue by SirLeezus** [Zrips/TradeMeAddon#4]
Errors: https://pastebin.com/MPt5rdk9

Commands: /trade, trade offer

Issue: When the command is ran it doesn't offer a trade message and sends errors in the console.

Versions:
Spigot 1.13.1
TradeMe 1.13.1

**Comment by SirGoldman-git** [comment]
He's been gone the last few days, I'm sure he'll get to it this weekend

**Comment by Zrips** [comment]
Should be resolved
