### ISSUE TITLE
Trademe error that cause items to be lost

### ISSUE THREAD

**Issue by Malachiel87** [Zrips/TradeMeAddon#43]
If you try to trade and the other guy keep to close windows, it will make the other guy lose all items puted in the trade window.
Error: https://gist.github.com/Malachiel87/ca935b2290ea0c0ad6ed324fa972578e
Version: Paper 1.8.8
Trademe 6.0.4.1
Video of another person that got the same issue: https://streamable.com/bffmrk

**Comment by Zrips** [comment]
Should be resolved with next build
