### ISSUE TITLE
Losing items due to Dupe logs

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TradeMeAddon#44]
[dupeLogs.zip](https://github.com/Zrips/TradeMeAddon/files/5612506/dupeLogs.zip)
I have similar issue to https://github.com/Zrips/TradeMeAddon/issues/43, prob. without error, but players are losing items by "dupes", but I don't understand, they normally wanted trade and this happens... Why are these dupe logs happen please and why players loose their items with them?

**Comment by Zrips** [comment]
Should be resolved with next official release
