### ISSUE TITLE
Bug with Jobs Reborn 

### ISSUE THREAD

**Issue by ElFrod0** [Zrips/TradeMeAddon#46]
Hello,

TradeMe plugin has small issue with Jobs Reborn plugin.
I am using max-level and vip-max-level in Jobs. TradeMe plugin doesn't respect that and only works with max-level. So when player can reach (for example) level 90 in certain Job (because of vip-max-level: 90). And max-level is set for 50. TradeMe doesn't allow to transfer more XP which would make the player go above level 50.

Cheers,
Michal

**Comment by mrfloris** [comment]
hi there,

both trademe and jobs reborn have updated to support 1.17, could you perhaps test on a test-setup if this issue is still happening for you?

**Comment by Zrips** [comment]
Will make small adjustments to take into consideration player max vip level as now we have appropriate API for it.
