### ISSUE TITLE
[Request/Suggestion] TradeMe Placeholder - %trademe_hasTradeToggledOn%

### ISSUE THREAD

**Issue by ghost** [Zrips/TradeMeAddon#53]
Incredibly useful placeholder for setting-GUI's etc:

type: boolean
**%trademe_hasTradeToggledOn% = true/false**  

_Function:
Placeholder will change the output if a player has done /trade toggle_

**Comment by WarnDa** [comment]
I agree with that 👍

**Comment by Zrips** [comment]
Will add with next update.
