### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#56]
Hello,

Blacklist do not work for me 

Player can add blacklisted item to the gui (by shift+clicking, or simply dragon and drop to the gui)

(they also got the actionbar 'blacklisted item' but it adds it to the trade)
using 'BlockedLore:' feature.

On latest plugin version (6.1.0.0), latest cmi release and paper 1.16.5
also tried 6.0.5.4, same issue

**Comment by WarnDa** [comment]
Player do not get any permission, no bypass, even no permission to trade items.

List of their permissions : 
<img width="1464" alt="Screenshot_5394" src="https://user-images.githubusercontent.com/31826333/127412652-c9d92982-c9fe-4378-ba64-8bb18bd2df82.png">

**Comment by Zrips** [comment]
Confirmed, will issue fix with todays update.
