### ISSUE TITLE
Some errors in gui

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#57]
I saw an error in some button gui : 

- The button "  Waiting:" is replaced by "  Accept:" in the gui
<img width="407" alt="Screenshot_5384" src="https://user-images.githubusercontent.com/31826333/127386945-e72587f5-fd69-415a-93a8-31b4f3d3cf2b.png">
<img width="593" alt="Screenshot_5385" src="https://user-images.githubusercontent.com/31826333/127386951-949d709c-de26-44b5-ac17-9813596d96f9.png">

**Comment by Zrips** [comment]
Confirmed, will fix with next build
