### ISSUE TITLE
Gui bug

### ISSUE THREAD

**Issue by WarnDa** [Zrips/TradeMeAddon#58]
Hello,

Using latest plugin version on paper 1.16.5, I saw an issue (it happened only 1 time on all my tests)
When the other player canceled trade, it opened me another gui with only 1 row
<img width="235" alt="Screenshot_5386" src="https://user-images.githubusercontent.com/31826333/127387519-1bc16801-093c-45c5-b60f-49039a628fe9.png">

I don't get more informations on how it happened :/

**Comment by Zrips** [comment]
Without option to reproduce this issue its hard to say what happen. if issue repeats, let me know, but i will need some more information in that case. Like what was traded or how that trade ended up.
