### ISSUE TITLE
Economy Bug

### ISSUE THREAD

**Issue by Anonymo99** [Zrips/TradeMeAddon#71]
Hello, i encountered the following bug regarding the money trade: When 2 players trade correctly with the blocks even when both players insert blocks and money as an exchange.
The problem occurs when 1 of the 2 players enters the exchange of money and only 1 of the 2 players inserts the blocks in the exchange inventory, the money is not removed from the player who exchanges, but the other player receives it.

**Comment by Zrips** [comment]
What type of economy plugin are you running?

**Comment by Anonymo99** [comment]
Private plugin

**Comment by Zrips** [comment]
If you could send me copy of that plugin over discord for testing I could more easily determine what went wrong. You could alternatively try testing it with some more common economy plugins out there which supports Vault to make sure that issue you are having isint related to your custom economy plugin.

**Comment by Anonymo99** [comment]
It looks like I solved it, thanks anyway.
