### ISSUE TITLE
Dupe issue

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TradeMeAddon#77]
Hi, running version 6.1.3.1 but I think it's possible to dupe here.

Some of the players issued /trade lot of times & duplicated items through it somehow, I could see in the log that they've bought something & then used /trade and had more items of it.

Here're the logs, may you could find there what exactly happened. 

[TradeLogs.zip](https://github.com/Zrips/TradeMeAddon/files/10460532/TradeLogs.zip)

**Comment by Zrips** [comment]
This is under investigation at the moment and patched version should come out tomorrow

**Comment by bobhenl** [comment]
Thanks so much!

**Comment by Zrips** [comment]
Gets fully resolved with next CMILib update and latest TradeMe version
